---
- name: Build and Deploy Insta_Likes Docker Container
  hosts: localhost
  connection: local
  tasks:
    - name: debug
      debug:
        msg: "{{ lookup('env','IGUN') }}"
        
    - name: Python Req's
      block:
      
        - name: Install PIP Debian
          apt:
            name: python3-pip
          when: ansible_facts['os_family'] == "Debian"
          
        - name: Install PIP EL
          dnf:
            name: python3-pip
          when: ansible_facts['os_family'] == "RedHat"
        
        - name: Python Module
          pip:
            name: docker-py
      
      become: yes
      become_method: sudo
  
    - name: Build and Run in Docker
      block:
      
        - name: Get InstaPy Image
          docker_image:
            name: instapy/instapy
            source: pull

        - name: Build Image
          docker_image:
            state: present
            name: insta_auto_likes:latest
            build:
              path: "{{ playbook_dir }}"
            source: build
    
        - name: Run Image
          docker_container:
            state: started
            name: insta_likes
            image: insta_likes:latest
            recreate: no
            env:
              IGUN: "{{ lookup('env','IGUN') }}"
              IGPW: "{{ lookup('env','IGPW') }}"
      
      become: yes
      become_method: sudo
    
